### ISSUE TITLE
fls in an emulated FS gives errors after a new file is created

### ISSUE THREAD

**Issue by jes** [hsoft/collapseos#56]
Any time I create a new file in the emulated filesystem, `fls` starts giving "Out of bounds" errors. Here's a minimal example, using a filesystem that just has a single empty file:

```
$ rm cfsin/*
$ touch cfsin/empty
$ shell/shell
Initializing filesystem
Collapse OS
> fls
empty
> fnew 1 dest
> fls
empty
dest
Out of bounds FSDEV addr request at 512 / 288
Out of bounds FSDEV addr request at 512 / 288
```

**Comment by jes** [comment]
I get the same "Out of bounds" error when trying to assemble CollapseOS from within the emulator:

```
$ shell/shell
Initializing filesystem
Collapse OS
> fls
blockdev.asm
glue.asm
fs.asm
kbd.asm
pgm.asm
mmap.asm
readme.txt
user.h
core.asm
sdc.asm
parse.asm
acia.asm
fs_cmds.asm
blockdev_cmds.asm
stdio.asm
hello.asm
zasm
ed
shell.asm
> fnew 1 dest
> fopn 0 glue.asm
> fopn 1 dest
> zasm 1 2
First pass
err.h
Out of bounds FSDEV addr request at 86016 / 85792
Out of bounds FSDEV addr request at 86016 / 85792
ERR 15
```

I will try and figure out what has gone wrong, just documenting the problem for now.

**Comment by jes** [comment]
So my current thought is that this isn't an error at all.

When cfspack writes a file to the disk image, it pads up to the end of the block with zeroes, but if the in-system file manipulation tools don't do this, then they won't cause fsdev_size to grow to the end of the block, which will mean trying to examine the start of the next block triggers this spurious message. Probably the solution is to just remove the message.

**Comment by jes** [comment]
Indeed, creating a new file only causes fsblkWriteMeta to be called, which only writes FS_METASIZE bytes (which is 32). A block is 256 bytes, and in both cases pasted above, the fsdev_ptr is 224 bytes past the end of fsdev_size (= 256 - 32, i.e. the start of the next block, minus the amount that was written into the last block).

So I'm saying the solution is to remove the message. In the meantime the "Out of bounds" error can simply be ignored.

**Comment by hsoft** [comment]
Sorry for the review's delay @jes, I'll look into is as soon as I have time. There's probably something wrong somewhere, but I think that this error is an actual error. This kind of IO shouldn't happen.

**Comment by jes** [comment]
There's some more explanation in the pull request. I think the best solution (and indeed, the solution I implemented) is to simply make the emulated device have a fixed size, instead of trying to make it grow every time you write 1 byte past the end of what has already been written.

**Comment by schierlm** [comment]
This bug is still present in https://github.com/hsoft/collapseos/commit/c002c692082cd964b18733c8c19bcf0c6ded9d2c, reproducably by the original example. I assumed I had to create two files now to get past the "stop block", but it even happens with one file (like in the original example). Two files make it worse, though.

**Comment by schierlm** [comment]
(cannot reopen the issue, though)

**Comment by hsoft** [comment]
It seems that I closed this a bit fast then.

**Comment by hsoft** [comment]
Now that I examine this closer, @jes was right. This is a spurious error. It's normal for the fsdev to get seek/read requests outside of its previous bounds.

I wrote these warnings for debugging at some point and they should be removed. I also closed #57 a bit too fast because except for the cfspack change which is now obsolete, the fix is good.

**Comment by hsoft** [comment]
Now it's fixed for real...
